# Generated by Django 2.0 on 2019-12-22 15:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Potholes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADDRESS', models.CharField(max_length=100)),
                ('REQUEST_DATE', models.DateField()),
                ('COMPLETION_DATE', models.DateField()),
                ('NUMBER_OF_POTHOLES_FILLED_ON_BLOCK', models.IntegerField()),
                ('LATITUDE', models.DecimalField(decimal_places=6, max_digits=9)),
                ('LONGITUDE', models.DecimalField(decimal_places=6, max_digits=9)),
                ('LOCATION', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
