# Generated by Django 2.0 on 2019-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_t_potholes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_potholes',
            name='COMPLETION_DATE',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='t_potholes',
            name='LATITUDE',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='t_potholes',
            name='LONGITUDE',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='t_potholes',
            name='REQUEST_DATE',
            field=models.DateTimeField(),
        ),
    ]
