# Generated by Django 3.0.1 on 2020-01-02 00:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20191222_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Density_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('poly_coordinate', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('density', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
            ],
        ),
    ]
