# Generated by Django 3.0.1 on 2020-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_density_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='density_map',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
    ]
