# Generated by Django 3.0.1 on 2020-01-05 18:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20200102_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='density_map',
            name='poly_coordinate',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
